# Generated by Django 3.0.2 on 2020-01-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.TextField()),
                ('Temperature', models.CharField(max_length=50)),
                ('Humidity', models.CharField(max_length=50)),
            ],
        ),
    ]
