# Generated by Django 3.0.2 on 2020-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictor',
            old_name='Place',
            new_name='Country',
        ),
        migrations.AddField(
            model_name='predictor',
            name='City',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
