# Generated by Django 3.0.2 on 2020-01-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200130_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictor',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='predictor',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='predictor',
            old_name='Humidity',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='predictor',
            old_name='Temperature',
            new_name='temperature',
        ),
    ]
